version: '3'
services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_BD=FirstBD
    ports:
    - 8888:5432
